### ISSUE TITLE
Using as a Library

### ISSUE THREAD

**Issue by sonicparke** [silvermine/dynamodb-table-sync#20]
I'm having issues understanding how to use this as a library. I'm able to get it to work using the cli but when I try to use it as a lib it doesn't seem to find any differences.
This is what I get back when using as a Lib:
```sh
{ 'us-east-1:my-slave-table': { extra: 0, sameAs: 0, differing: 0, missing: 0 } }
```

```js
exports.handler = async () => {
      const sync = new Synchronizer(
        { region: 'us-east-1', name: 'my-master-table' },
        [{ region: 'us-east-1', name: 'my-slave-table' }],
        {
          writeMissing: true,
          writeDiffering: true
        }
      );
      console.log(sync._stats)
};
```

And using CLI:
![image](https://user-images.githubusercontent.com/1139721/83983614-613c0a00-a8f5-11ea-9874-d1da27d88bc2.png)

**Comment by jthomerson** [comment]
@sonicparke yeah, looks like we were missing something in the docs. Check out the update.

**Comment by sonicparke** [comment]
> @sonicparke yeah, looks like we were missing something in the docs. Check out the update.

Awesome! Thanks for the quick response!
